// Curated registry of well-known LSP servers used to populate the
// "Browse registry" picker on the LSP settings page.

export interface LspRegistryEntry {
  name: string;
  slug: string;
  language: string;
  description: string;
  command: string;
  args: string[];
  root_markers: string[];
  // File extensions handled by this server, mapped to LSP language IDs.
  // grok-cli's lsp.json requires extensionToLanguage to know which files trigger
  // this server. Each key includes the leading dot (e.g. ".ts").
  extensions: Record<string, string>;
  install_hint?: string;
  url_docs?: string;
  official: boolean;
}

export const LSP_REGISTRY: LspRegistryEntry[] = [
  {
    name: 'typescript-language-server',
    slug: 'typescript',
    language: 'typescript',
    description: 'TypeScript and JavaScript language server (Microsoft tsserver wrapper).',
    command: 'typescript-language-server',
    args: ['--stdio'],
    root_markers: ['package.json', 'tsconfig.json', 'jsconfig.json'],
    extensions: {
      '.ts': 'typescript',
      '.tsx': 'typescriptreact',
      '.js': 'javascript',
      '.jsx': 'javascriptreact',
      '.mjs': 'javascript',
      '.cjs': 'javascript',
    },
    install_hint: 'npm install -g typescript-language-server typescript',
    url_docs: 'https://github.com/typescript-language-server/typescript-language-server',
    official: true,
  },
  {
    name: 'pyright',
    slug: 'pyright',
    language: 'python',
    description: 'Microsoft Pyright static type checker and language server for Python.',
    command: 'pyright-langserver',
    args: ['--stdio'],
    root_markers: ['pyproject.toml', 'setup.py', 'requirements.txt', 'Pipfile'],
    extensions: { '.py': 'python', '.pyi': 'python' },
    install_hint: 'npm install -g pyright',
    url_docs: 'https://github.com/microsoft/pyright',
    official: true,
  },
  {
    name: 'python-lsp-server',
    slug: 'pylsp',
    language: 'python',
    description: 'Community Python LSP (pylsp) with pluggable linters and formatters.',
    command: 'pylsp',
    args: [],
    root_markers: ['pyproject.toml', 'setup.py', 'requirements.txt', 'Pipfile'],
    extensions: { '.py': 'python', '.pyi': 'python' },
    install_hint: 'pip install python-lsp-server',
    url_docs: 'https://github.com/python-lsp/python-lsp-server',
    official: true,
  },
  {
    name: 'rust-analyzer',
    slug: 'rust-analyzer',
    language: 'rust',
    description: 'Official Rust language server.',
    command: 'rust-analyzer',
    args: [],
    root_markers: ['Cargo.toml'],
    extensions: { '.rs': 'rust' },
    install_hint: 'rustup component add rust-analyzer',
    url_docs: 'https://rust-analyzer.github.io/',
    official: true,
  },
  {
    name: 'gopls',
    slug: 'gopls',
    language: 'go',
    description: 'Official Go language server maintained by the Go team.',
    command: 'gopls',
    args: [],
    root_markers: ['go.mod', 'go.work'],
    extensions: { '.go': 'go' },
    install_hint: 'go install golang.org/x/tools/gopls@latest',
    url_docs: 'https://pkg.go.dev/golang.org/x/tools/gopls',
    official: true,
  },
  {
    name: 'clangd',
    slug: 'clangd',
    language: 'cpp',
    description: 'LLVM-based language server for C, C++, Objective-C, and CUDA.',
    command: 'clangd',
    args: [],
    root_markers: ['compile_commands.json', '.clangd', 'CMakeLists.txt'],
    extensions: {
      '.c': 'c',
      '.h': 'c',
      '.cc': 'cpp',
      '.cpp': 'cpp',
      '.cxx': 'cpp',
      '.hpp': 'cpp',
      '.hh': 'cpp',
      '.m': 'objective-c',
      '.mm': 'objective-cpp',
    },
    install_hint: 'install via your system package manager (apt/brew install clangd)',
    url_docs: 'https://clangd.llvm.org/',
    official: true,
  },
  {
    name: 'jdtls',
    slug: 'jdtls',
    language: 'java',
    description: 'Eclipse JDT Language Server for Java projects.',
    command: 'jdtls',
    args: [],
    root_markers: ['pom.xml', 'build.gradle', 'build.gradle.kts', '.project'],
    extensions: { '.java': 'java' },
    install_hint: 'install via mason.nvim or download from https://download.eclipse.org/jdtls/',
    url_docs: 'https://github.com/eclipse-jdtls/eclipse.jdt.ls',
    official: true,
  },
  {
    name: 'solargraph',
    slug: 'solargraph',
    language: 'ruby',
    description: 'Ruby language server with YARD-based type and doc support.',
    command: 'solargraph',
    args: ['stdio'],
    root_markers: ['Gemfile', '.solargraph.yml'],
    extensions: { '.rb': 'ruby', '.rake': 'ruby', '.gemspec': 'ruby' },
    install_hint: 'gem install solargraph',
    url_docs: 'https://solargraph.org/',
    official: true,
  },
  {
    name: 'lua-language-server',
    slug: 'lua-language-server',
    language: 'lua',
    description: 'Lua language server developed by sumneko.',
    command: 'lua-language-server',
    args: [],
    root_markers: ['.luarc.json', '.luarc.jsonc', 'stylua.toml', 'selene.toml'],
    extensions: { '.lua': 'lua' },
    install_hint: 'install via your system package manager or https://luals.github.io/',
    url_docs: 'https://luals.github.io/',
    official: true,
  },
  {
    name: 'bash-language-server',
    slug: 'bash',
    language: 'bash',
    description: 'Language server for Bash and POSIX shell scripts.',
    command: 'bash-language-server',
    args: ['start'],
    root_markers: ['.bashrc', '.bash_profile', '.git'],
    extensions: { '.sh': 'shellscript', '.bash': 'shellscript' },
    install_hint: 'npm install -g bash-language-server',
    url_docs: 'https://github.com/bash-lsp/bash-language-server',
    official: true,
  },
  {
    name: 'vscode-html-language-server',
    slug: 'html',
    language: 'html',
    description: 'HTML language server extracted from VS Code.',
    command: 'vscode-html-language-server',
    args: ['--stdio'],
    root_markers: ['package.json', '.git'],
    extensions: { '.html': 'html', '.htm': 'html' },
    install_hint: 'npm install -g vscode-langservers-extracted',
    url_docs: 'https://github.com/hrsh7th/vscode-langservers-extracted',
    official: true,
  },
  {
    name: 'vscode-css-language-server',
    slug: 'css',
    language: 'css',
    description: 'CSS, SCSS, and LESS language server extracted from VS Code.',
    command: 'vscode-css-language-server',
    args: ['--stdio'],
    root_markers: ['package.json', '.git'],
    extensions: { '.css': 'css', '.scss': 'scss', '.less': 'less' },
    install_hint: 'npm install -g vscode-langservers-extracted',
    url_docs: 'https://github.com/hrsh7th/vscode-langservers-extracted',
    official: true,
  },
  {
    name: 'vscode-json-language-server',
    slug: 'json',
    language: 'json',
    description: 'JSON and JSONC language server extracted from VS Code.',
    command: 'vscode-json-language-server',
    args: ['--stdio'],
    root_markers: ['package.json', '.git'],
    extensions: { '.json': 'json', '.jsonc': 'jsonc' },
    install_hint: 'npm install -g vscode-langservers-extracted',
    url_docs: 'https://github.com/hrsh7th/vscode-langservers-extracted',
    official: true,
  },
  {
    name: 'yaml-language-server',
    slug: 'yaml',
    language: 'yaml',
    description: 'Red Hat YAML language server with JSON Schema validation.',
    command: 'yaml-language-server',
    args: ['--stdio'],
    root_markers: ['.yamllint', '.yaml-language-server', '.git'],
    extensions: { '.yaml': 'yaml', '.yml': 'yaml' },
    install_hint: 'npm install -g yaml-language-server',
    url_docs: 'https://github.com/redhat-developer/yaml-language-server',
    official: true,
  },
  {
    name: 'tailwindcss-language-server',
    slug: 'tailwind',
    language: 'tailwindcss',
    description: 'Tailwind CSS class completions, hover docs, and lint diagnostics.',
    command: 'tailwindcss-language-server',
    args: ['--stdio'],
    root_markers: ['tailwind.config.js', 'tailwind.config.ts', 'tailwind.config.cjs', 'tailwind.config.mjs'],
    extensions: { '.css': 'css', '.html': 'html', '.tsx': 'typescriptreact', '.jsx': 'javascriptreact' },
    install_hint: 'npm install -g @tailwindcss/language-server',
    url_docs: 'https://github.com/tailwindlabs/tailwindcss-intellisense',
    official: true,
  },
];
